import { Inter } from "next/font/google";
import "./globals.css";
import { CssBaseline, ThemeProvider } from "@mui/material";
import theme from "@/theme";
import { QueryProviders } from "./QueryProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <QueryProviders>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Toaster />
            {children}
          </ThemeProvider>
        </QueryProviders>
      </body>
    </html>
  );
}
